### ISSUE TITLE
Composer dependency on 4.0.0-beta1

### ISSUE THREAD

**Issue by ruudboon** [woohoolabs/yin-middleware#2]
When installing the alpha version you won't be able to use the yin alpha version.
```
- woohoolabs/yin-middleware 4.0.0-beta1 requires woohoolabs/yin 4.0.x-dev as 4.0.0 -> satisfiable by woohoolabs/yin[4.0.x-dev] but these conflict with your requirements or minimum-stability.
```
Require
```
"require": {
        "php": ">=7.3",
        "zendframework/zend-diactoros": "^1.7.0",
        "woohoolabs/yin": "^4.0.0-beta1",
        "woohoolabs/yin-middleware": "^4.0.0-beta1"
    },
```

**Comment by kocsismate** [comment]
Hi!

The problem is that Yin Middleware 4.0-beta1 was tagged before Yin 4.0-beta1, so unfortunately it requires "Yin 4.0.x-dev".

As a quick fix, I could create a beta 2 of Yin and Yin Middleware, but my plan is to release a final version of both packages very soon. If your code is not yet in production then you can safely use "woohoolabs/yin": "^4.0.x-dev" in your composer because it only contains a fix of a regression on top of beta 1.

But if you are not ok with this quick fix, I can release the beta 2 of Yin and Yin Middleware. :)

**Comment by kocsismate** [comment]
PS: it came to my mind that if the PR for https://github.com/woohoolabs/yin/issues/80 will be done then I will definitely have to release a beta 2 of both packages.

**Comment by ruudboon** [comment]
No rush, I've fixed locally to keep working. Looking fwd to the final release
