### ISSUE TITLE
seld/jsonlint is incorrectly a "dev" dependency

### ISSUE THREAD

**Issue by DavidCarrington** [woohoolabs/yin-middleware#4]
seld/jsonlint is required for people wanting to make use of these Middleware, so should be a production dependency.

**Comment by kocsismate** [comment]
Hey @DavidCarrington ,

It's not entirely true. Seld/jsonlint as well as justinrainbow/json-schema are optional dependencies because they are not necessary to install when e.g. only the `JsonApiDispatcherMiddleware` or the `JsonApiExceptionHandlerMiddleware` are used.

Also, in order to be more transparent about these optional dependencies, Yin marked them as suggested packages ( https://github.com/woohoolabs/yin/blob/master/composer.json#L35).

I think the situation could only be improved by also mentioning that these packages should also be installed if you want to use the validation middleware. Here is an example where I did it in the past: https://github.com/woohoolabs/harmony#install-the-optional-dependencies

What do you think? Do you want to add this section to the readme (e.g. because of Hacktoberfest ^^) or give me the possibility to do so? :)

**Comment by kocsismate** [comment]
@DavidCarrington I've just extended the read me with the notes I suggested above.
