### ISSUE TITLE
Is it really PSR-15?

### ISSUE THREAD

**Issue by DavidCarrington** [woohoolabs/yin-middleware#5]
If there's an expectation of a specific JsonApiRequestInterface rather than any PSR-7 Request, are these Middleware really PSR-15 compliant?

You could check for a PSR-7 Request and wrap it internally without expecting the custom interface to be passed in, which means you could drop these Middleware more easily into other frameworks.

**Comment by kocsismate** [comment]
@DavidCarrington Thanks for raising my attention for the problem. I think automatic conversion isn't the best solution (because people often need passing some configuration to the request, which would be cumbersome in this case), but I think creating a compatibility middleware will help the situation.

Please see my referenced commit for further details. I am curious about your opinion.
